export const DOC_CREATE_PENDING = "DOC CREATE PENDING";
export const DOC_CREATE_SUCCESS = "DOC CREATE SUCCESS";
export const DOC_CREATE_FAILURE = "DOC CREATE FAILURE";

export const GET_DOCCONTENT_PENDING = "GET DOCCONTENT PENDING";
export const GET_DOCCONTENT_SUCCESS = "GET DOCCONTENT SUCCESS";
export const GET_DOCCONTENT_FAILURE = "GET DOCCONTENT FAILURE";
